In [11]:
import numpy as np
list1 = [2,3,44,53,23]
arr = np.array(list1)
print(arr)
print(arr.dtype)
print(arr.ndim)
print(np.__version__)


[ 2  3 44 53 23]
int64
1
2.1.2


In [12]:
T1 = (1,24.55,44,432,13)
arr = np.array(T1)
print(T1)

(1, 24.55, 44, 432, 13)


In [15]:
d1 = {"id" :2002, "name" : "Kamini"}
print(d1)

{'id': 2002, 'name': 'Kamini'}


In [17]:
#print(d1.dtype)
arr = np.array(d1)
print(arr)

{'id': 2002, 'name': 'Kamini'}


In [19]:
print(arr.dtype)

object


In [20]:
print(type(arr))

<class 'numpy.ndarray'>


In [21]:
print(arr.ndim)

0


In [22]:
twoD = [[1,2,3],[14,56,33]]
arr2d = np.array(twoD)
print(arr2d)

[[ 1  2  3]
 [14 56 33]]


In [23]:
print(type(arr2d))

<class 'numpy.ndarray'>


In [24]:
print(arr2d.dtype)

int64


In [28]:
arr = np.array([1,3,4,5,4,5,63,22,22])
print(arr)
newarr = arr.astype('i')
print(type(arr))
print(newarr)
print(newarr.dtype)

[ 1  3  4  5  4  5 63 22 22]
<class 'numpy.ndarray'>
[ 1  3  4  5  4  5 63 22 22]
int32


In [29]:
# copy view

arr = np.array([1,2,3,4,211,1])
x = arr.copy()
arr[0] = 30
print("original arr", arr,"dupe arr", arr)

original arr [ 30   2   3   4 211   1] dupe arr [ 30   2   3   4 211   1]


In [34]:
arr = np.array([1,2,3,4,5])
x = arr.view()
y = arr.copy()
arr[0]=30
print("original", arr)
print(x.view)
print(x.base)
print(y.base)

print("updated view array",x)

original [30  2  3  4  5]
<built-in method view of numpy.ndarray object at 0x1181165b0>
[30  2  3  4  5]
None
updated view array [30  2  3  4  5]


In [35]:
l1 = [[1,2,3],[4,5,6]]
arr1 = np.array(l1)
print(arr1)


[[1 2 3]
 [4 5 6]]


In [36]:
print(arr1.shape)

(2, 3)


In [37]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in np.nditer(arr1):
    print(x)

1
2
3
4
5
6
7
8
9


In [42]:
arr2 = np.array([1,2,3,4])
arr3 = np.array([333,422,213,222])
arr4 = np.concatenate((arr3, arr2))
arr5 = np.concatenate((arr3,arr2), axis=0)

print(arr4)
print(arr5)


[333 422 213 222   1   2   3   4]
[333 422 213 222   1   2   3   4]
